python main.py \
  --pretrained_model "mistralai/Mistral-7B-Instruct-v0.3" \
  --config_path "config_cast_180m.json" \
  --output_dir "cast_180m" \
  --max_steps=10000 \
  --gradient_checkpointing=True \
  --logging_steps=100 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --per_device_train_batch_size "128" \
  --learning_rate 2e-4 \
  --logging_dir 'logs' \
  --max_seq_length 512 \
  --bf16 True \
  --save_steps 10000 \
  --lr_scheduler_type cosine \
  --model_output_path "cast_checkpoint_180m"